CREATE TABLE IF NOT EXISTS cheques (
  id                    INT           NOT NULL AUTO_INCREMENT,
  tipo                  ENUM('recibido','emitido') NOT NULL,
  numero                VARCHAR(30)   NOT NULL,
  banco                 VARCHAR(100)  NOT NULL,
  librador              VARCHAR(150)  DEFAULT NULL,
  beneficiario          VARCHAR(150)  DEFAULT NULL,
  cuit                  VARCHAR(13)   DEFAULT NULL,
  monto                 DECIMAL(15,2) NOT NULL,
  fecha_emision         DATE          DEFAULT NULL,
  fecha_vencimiento     DATE          NOT NULL,
  estado                ENUM('cartera','depositado','endosado','rechazado','pendiente','debitado') NOT NULL,
  venta_id              INT           DEFAULT NULL,
  cliente_id            INT           DEFAULT NULL,
  cc_movimiento_id      INT           DEFAULT NULL,
  banco_destino         VARCHAR(100)  DEFAULT NULL,
  fecha_deposito        DATE          DEFAULT NULL,
  proveedor_id          INT           DEFAULT NULL,
  cc_prov_movimiento_id INT           DEFAULT NULL,
  notas                 TEXT          DEFAULT NULL,
  sucursal_id           INT           NOT NULL DEFAULT 1,
  created_at            TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at            TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_tipo_estado      (tipo, estado),
  KEY idx_vencimiento      (fecha_vencimiento),
  KEY idx_cliente          (cliente_id),
  KEY idx_proveedor        (proveedor_id),
  KEY idx_venta            (venta_id),
  KEY idx_cc_mov           (cc_movimiento_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
